(require 'cask "~/.cask/cask.el")
(cask-initialize)
(require 'pallet)
(add-to-list 'load-path "~/.emacs.d/custom")

(load "00common-setup.el")
(load "01ruby.el")
;(load "02org.el")
(load "03auto-complete.el")
;(load "04web-mode.el")
(load "05projectile.el")
(load "06documentation.el")
(load "07javascript.el")
(load "08anything.el")
(load "09html.el")
